In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("DrDoS_LDAP.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
dataset.dtypes

Unnamed: 0           int64
Flow ID             object
 Source IP          object
 Source Port         int64
 Destination IP     object
                    ...
 Idle Max          float64
 Idle Min          float64
SimillarHTTP        object
 Inbound             int64
 Label              object
Length: 88, dtype: object

In [5]:
dataset.describe()

,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
count,2.181542e+06,2.181542e+06,2.181542e+06,2.181542e+06,2.181542e+06,2.181542e+06,2.181542e+06,2.181542e+06,2.181542e+06,2.181542e+06,...,2.181542e+06,2.181542e+06,2181542.0,2.181542e+06,2.181542e+06,2.181542e+06,2181542.0,2.181542e+06,2.181542e+06,2.181542e+06
mean,1.704283e+04,8.531110e+02,3.276972e+04,1.699132e+01,6.698804e+02,4.524823e+00,3.328380e-03,2.933517e+03,9.575672e-01,1.462711e+03,...,-5.237284e+07,9.434153e-03,0.0,9.434153e-03,9.434153e-03,3.613463e+01,0.0,3.613463e+01,3.613463e+01,9.990319e-01
std,9.840009e+03,1.947001e+03,1.892384e+04,3.242059e-01,6.448156e+04,4.648172e+02,2.942144e-01,3.031092e+02,2.451018e+02,6.399144e+01,...,2.300741e+08,1.385786e+01,0.0,1.385786e+01,1.385786e+01,1.565532e+04,0.0,1.565532e+04,1.565532e+04,3.109961e-02
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,-1.408238e+09,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.521000e+03,6.610000e+02,1.640000e+04,1.700000e+01,1.000000e+00,2.000000e+00,0.000000e+00,2.944000e+03,0.000000e+00,1.472000e+03,...,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,1.000000e+00
50%,1.704300e+04,8.110000e+02,3.277200e+04,1.700000e+01,1.000000e+00,2.000000e+00,0.000000e+00,2.944000e+03,0.000000e+00,1.472000e+03,...,8.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,1.000000e+00
75%,2.556400e+04,9.000000e+02,4.915900e+04,1.700000e+01,2.000000e+00,2.000000e+00,0.000000e+00,2.944000e+03,0.000000e+00,1.472000e+03,...,2.000000e+01,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,1.000000e+00
max,3.420300e+04,6.551000e+04,6.553500e+04,1.700000e+01,1.116618e+07,8.622100e+04,1.810000e+02,5.888000e+04,1.746340e+05,2.980000e+03,...,1.480000e+03,2.046800e+04,0.0,2.046800e+04,2.046800e+04,9.258158e+06,0.0,9.258158e+06,9.258158e+06,1.000000e+00

In [6]:
dataset.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,21010,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:22:40.254769,9141643,85894,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
1,20932,172.16.0.5-192.168.50.1-900-1808-17,172.16.0.5,900,192.168.50.1,1808,17,2018-12-01 11:22:40.255361,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2,27876,172.16.0.5-192.168.50.1-900-58766-17,172.16.0.5,900,192.168.50.1,58766,17,2018-12-01 11:22:40.255568,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
3,24270,172.16.0.5-192.168.50.1-900-35228-17,172.16.0.5,900,192.168.50.1,35228,17,2018-12-01 11:22:40.256113,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
4,5109,172.16.0.5-192.168.50.1-900-44969-17,172.16.0.5,900,192.168.50.1,44969,17,2018-12-01 11:22:40.256285,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP

In [8]:
dataset.columns

Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')

In [9]:
dataset[" Label"]

0          DrDoS_LDAP
1          DrDoS_LDAP
2          DrDoS_LDAP
3          DrDoS_LDAP
4          DrDoS_LDAP
              ...
2181537    DrDoS_LDAP
2181538    DrDoS_LDAP
2181539    DrDoS_LDAP
2181540    DrDoS_LDAP
2181541    DrDoS_LDAP
Name:  Label, Length: 2181542, dtype: object

In [10]:
dataset.dropna()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,21010,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:22:40.254769,9141643,85894,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
1,20932,172.16.0.5-192.168.50.1-900-1808-17,172.16.0.5,900,192.168.50.1,1808,17,2018-12-01 11:22:40.255361,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2,27876,172.16.0.5-192.168.50.1-900-58766-17,172.16.0.5,900,192.168.50.1,58766,17,2018-12-01 11:22:40.255568,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
3,24270,172.16.0.5-192.168.50.1-900-35228-17,172.16.0.5,900,192.168.50.1,35228,17,2018-12-01 11:22:40.256113,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
4,5109,172.16.0.5-192.168.50.1-900-44969-17,172.16.0.5,900,192.168.50.1,44969,17,2018-12-01 11:22:40.256285,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2181537,4277,172.16.0.5-192.168.50.1-846-44562-17,172.16.0.5,846,192.168.50.1,44562,17,2018-12-01 11:32:32.914224,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2181538,20369,172.16.0.5-192.168.50.1-900-87-17,172.16.0.5,900,192.168.50.1,87,17,2018-12-01 11:32:32.914273,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2181539,33671,172.16.0.5-192.168.50.1-847-1622-17,172.16.0.5,847,192.168.50.1,1622,17,2018-12-01 11:32:32.914438,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2181540,2167,172.16.0.5-192.168.50.1-848-16197-17,172.16.0.5,848,192.168.50.1,16197,17,2018-12-01 11:32:32.915067,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2181541,15050,172.16.0.5-192.168.50.1-849-7758-17,172.16.0.5,849,192.168.50.1,7758,17,2018-12-01 11:32:32.915361,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP

In [17]:
benign_data = dataset[dataset[" Label"] == "BENIGN"]

In [18]:
benign_data.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
2389,21243,192.168.50.6-23.194.142.213-57215-443-6,192.168.50.6,57215,23.194.142.213,443,6,2018-12-01 11:22:40.970628,20740,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
6050,18666,192.168.50.253-224.0.0.5-0-0-0,192.168.50.253,0,224.0.0.5,0,0,2018-12-01 11:22:41.955234,5,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
13522,15346,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,2018-12-01 11:22:43.923507,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
30496,160,192.168.50.254-224.0.0.5-0-0-0,192.168.50.254,0,224.0.0.5,0,0,2018-12-01 11:22:48.452989,3,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
34745,19686,192.168.50.8-125.56.201.105-59307-80-6,192.168.50.8,59307,125.56.201.105,80,6,2018-12-01 11:22:49.599759,173888,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN

In [19]:
benign_data.shape

(1612, 88)

In [20]:
benign_data.to_csv("benign_LDAP.csv")

In [23]:
LDAP_data = dataset[dataset[" Label"] == "DrDoS_LDAP"]

In [25]:
LDAP = LDAP_data.head(10000)

In [26]:
LDAP.to_csv("LDAP_data.csv")

In [27]:
dataset1 = pd.read_csv("DrDoS_MSSQL.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [28]:
dataset1.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,139,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:32:32.915441,119151083,60959,...,2.853681e+07,67834732.0,4024278.0,5975510.0,98.183502,5975622.0,5975358.0,0,1,DrDoS_MSSQL
1,38385,172.16.0.5-192.168.50.1-850-20345-17,172.16.0.5,850,192.168.50.1,20345,17,2018-12-01 11:32:32.915442,1,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
2,27033,172.16.0.5-192.168.50.1-851-21631-17,172.16.0.5,851,192.168.50.1,21631,17,2018-12-01 11:32:32.915578,1,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
3,34348,172.16.0.5-192.168.50.1-852-15332-17,172.16.0.5,852,192.168.50.1,15332,17,2018-12-01 11:32:32.915773,2,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
4,19225,172.16.0.5-192.168.50.1-853-41853-17,172.16.0.5,853,192.168.50.1,41853,17,2018-12-01 11:32:32.916114,2,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL

In [30]:
dataset1.shape

(4524498, 88)

In [31]:
benign_data_mssql = dataset1[dataset1[" Label"] == "BENIGN"]

In [32]:
benign_data_mssql.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
7312,142,192.168.50.253-224.0.0.5-0-0-0,192.168.50.253,0,224.0.0.5,0,0,2018-12-01 11:32:35.074888,112597315,52,...,0.717741,7.0,4.0,9383103.25,257958.305025,9810774.0,9048572.0,0,0,BENIGN
16189,0,192.168.50.6-104.88.60.48-57271-80-6,192.168.50.6,57271,104.88.60.48,80,6,2018-12-01 11:32:37.701019,2,2,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,0,BENIGN
16190,1,192.168.50.6-104.88.29.90-57270-80-6,192.168.50.6,57270,104.88.29.90,80,6,2018-12-01 11:32:37.701021,1,2,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,0,BENIGN
16191,2,192.168.50.6-104.88.29.90-57272-80-6,192.168.50.6,57272,104.88.29.90,80,6,2018-12-01 11:32:37.701023,1,2,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,0,BENIGN
16260,3,192.168.50.6-104.88.60.48-57271-80-6,104.88.60.48,80,192.168.50.6,57271,6,2018-12-01 11:32:37.721493,1,2,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,1,BENIGN

In [33]:
benign_data_mssql.shape

(2006, 88)

In [34]:
benign_data_mssql.to_csv("benign_mssql.csv")

In [35]:
mssql_data = dataset1[dataset1[" Label"] == "DrDoS_MSSQL"]

In [36]:
mssql_data.shape

(4522492, 88)

In [40]:
mssql.to_csv("mssql_data.csv")

In [38]:
mssql = mssql_data.head(10000)

In [39]:
mssql.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,139,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:32:32.915441,119151083,60959,...,2.853681e+07,67834732.0,4024278.0,5975510.0,98.183502,5975622.0,5975358.0,0,1,DrDoS_MSSQL
1,38385,172.16.0.5-192.168.50.1-850-20345-17,172.16.0.5,850,192.168.50.1,20345,17,2018-12-01 11:32:32.915442,1,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
2,27033,172.16.0.5-192.168.50.1-851-21631-17,172.16.0.5,851,192.168.50.1,21631,17,2018-12-01 11:32:32.915578,1,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
3,34348,172.16.0.5-192.168.50.1-852-15332-17,172.16.0.5,852,192.168.50.1,15332,17,2018-12-01 11:32:32.915773,2,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
4,19225,172.16.0.5-192.168.50.1-853-41853-17,172.16.0.5,853,192.168.50.1,41853,17,2018-12-01 11:32:32.916114,2,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL

In [41]:
dataset2 = pd.read_csv("DrDoS_NetBIOS.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [42]:
dataset2.shape

(4094986, 88)

In [43]:
dataset2.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,256565,172.16.0.5-192.168.50.1-34012-2334-17,172.16.0.5,34012,192.168.50.1,2334,17,2018-12-01 11:47:08.463789,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
1,252918,172.16.0.5-192.168.50.1-34013-50170-17,172.16.0.5,34013,192.168.50.1,50170,17,2018-12-01 11:47:08.464316,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
2,174257,172.16.0.5-192.168.50.1-34014-61534-17,172.16.0.5,34014,192.168.50.1,61534,17,2018-12-01 11:47:08.464472,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
3,185193,172.16.0.5-192.168.50.1-34015-8930-17,172.16.0.5,34015,192.168.50.1,8930,17,2018-12-01 11:47:08.464520,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
4,198671,172.16.0.5-192.168.50.1-34016-33040-17,172.16.0.5,34016,192.168.50.1,33040,17,2018-12-01 11:47:08.464925,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS

In [44]:
benign_data_bios = dataset2[dataset2[" Label"] == "BENIGN"]

In [45]:
benign_data_bios.shape

(1707, 88)

In [46]:
benign_data_bios.to_csv("benign_bios")

In [47]:
bios_data = dataset2[dataset2[" Label"] == "DrDoS_NetBIOS"]

In [48]:
bios = bios_data.head(10000)

In [49]:
bios.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,256565,172.16.0.5-192.168.50.1-34012-2334-17,172.16.0.5,34012,192.168.50.1,2334,17,2018-12-01 11:47:08.463789,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
1,252918,172.16.0.5-192.168.50.1-34013-50170-17,172.16.0.5,34013,192.168.50.1,50170,17,2018-12-01 11:47:08.464316,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
2,174257,172.16.0.5-192.168.50.1-34014-61534-17,172.16.0.5,34014,192.168.50.1,61534,17,2018-12-01 11:47:08.464472,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
3,185193,172.16.0.5-192.168.50.1-34015-8930-17,172.16.0.5,34015,192.168.50.1,8930,17,2018-12-01 11:47:08.464520,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
4,198671,172.16.0.5-192.168.50.1-34016-33040-17,172.16.0.5,34016,192.168.50.1,33040,17,2018-12-01 11:47:08.464925,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS

In [50]:
bios.to_csv("bios_data.csv")

In [51]:
dataset3 = pd.read_csv("DrDoS_NTP.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [52]:
dataset3.shape

(1217007, 88)

In [53]:
benign_data_ntp = dataset2[dataset2[" Label"] == "BENIGN"]

In [54]:
benign_data_ntp.shape

(1707, 88)

In [55]:
benign_data_ntp.to_csv("benign_n.csv")

In [58]:
dataset3.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,172.16.0.5-192.168.50.1-60675-80-6,172.16.0.5,60675,192.168.50.1,80,6,2018-12-01 09:17:11.183810,5220876,12,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,205.174.165.72/c.php,1,DrDoS_NTP
1,7,172.16.0.5-192.168.50.1-60676-80-6,172.16.0.5,60676,192.168.50.1,80,6,2018-12-01 09:17:11.205636,12644252,5,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_NTP
2,12858,192.168.50.7-65.55.163.78-50458-443-6,65.55.163.78,443,192.168.50.7,50458,6,2018-12-01 09:17:12.634569,3,2,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,BENIGN
3,10191,192.168.50.7-65.55.163.78-50465-443-6,65.55.163.78,443,192.168.50.7,50465,6,2018-12-01 09:17:13.458370,3,2,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,BENIGN
4,239,192.168.50.253-224.0.0.5-0-0-0,192.168.50.253,0,224.0.0.5,0,0,2018-12-01 09:17:13.470913,114329232,52,...,2.466441,15.0,6.0,9527428.0,248706.681286,9950741.0,9092248.0,0,0,BENIGN

In [63]:
ntp_data = dataset3[dataset3[" Label"] == "DrDoS_NTP"]

In [64]:
ntp_data.shape

(1202642, 88)

In [66]:
ntp = ntp_data.head(10000)
ntp.shape

(10000, 88)

In [67]:
ntp.to_csv("ntp_data.csv")

In [68]:
dataset4 = pd.read_csv("DrDoS_SNMP.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [70]:
dataset4.shape

(5161377, 88)

In [71]:
benign_data_snmp = dataset4[dataset4[" Label"] == "BENIGN"]

In [72]:
benign_data_snmp.shape

(1507, 88)

In [73]:
benign_data_snmp.to_csv("benign_snmp.csv")

In [74]:
dataset4.head(2)

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,109857,172.16.0.5-192.168.50.1-528-47330-17,172.16.0.5,528,192.168.50.1,47330,17,2018-12-01 12:00:13.902782,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SNMP
1,238192,172.16.0.5-192.168.50.1-529-26888-17,172.16.0.5,529,192.168.50.1,26888,17,2018-12-01 12:00:13.902785,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SNMP

In [75]:
snmp_data = dataset4[dataset4[" Label"] == "DrDoS_SNMP"]

In [76]:
snmp_data.shape

(5159870, 88)

In [77]:
snmp = snmp_data.head(10000)

In [79]:
snmp.shape

(10000, 88)

In [80]:
snmp.to_csv("snmp_data.csv")

In [81]:
dataset5 = pd.read_csv("DrDoS_SSDP.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [82]:
dataset5.shape

(2611374, 88)

In [83]:
benign_data_ssdp = dataset5[dataset5[" Label"] == "BENIGN"]

In [84]:
benign_data_ssdp.shape

(763, 88)

In [85]:
benign_data_ssdp.to_csv("benign_ssdp.csv")

In [86]:
dataset5.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,72,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 12:23:13.663425,119714230,49476,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP
1,55171,172.16.0.5-192.168.50.1-700-36081-17,172.16.0.5,700,192.168.50.1,36081,17,2018-12-01 12:23:13.663475,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP
2,39545,172.16.0.5-192.168.50.1-701-25269-17,172.16.0.5,701,192.168.50.1,25269,17,2018-12-01 12:23:13.663526,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP
3,20334,172.16.0.5-192.168.50.1-702-2533-17,172.16.0.5,702,192.168.50.1,2533,17,2018-12-01 12:23:13.663622,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP
4,18397,172.16.0.5-192.168.50.1-703-34942-17,172.16.0.5,703,192.168.50.1,34942,17,2018-12-01 12:23:13.663844,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP

In [89]:
ssdp_data = dataset5[dataset5[" Label"] == "DrDoS_SSDP"]

In [90]:
ssdp_data.shape

(2610611, 88)

In [91]:
ssdp = ssdp_data.head(10000)

In [92]:
ssdp.shape

(10000, 88)

In [93]:
ssdp.to_csv("ssdp_data.csv")

In [94]:
dataset6 = pd.read_csv("DrDoS_UDP.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [95]:
dataset6.shape

(3136802, 88)

In [96]:
benign_data_udp = dataset6[dataset6[" Label"] == "BENIGN"]

In [97]:
benign_data_udp.shape

(2157, 88)

In [98]:
benign_data_udp.to_csv("benign_udp.csv")

In [99]:
udp_data = dataset6[dataset6[" Label"] == "DrDoS_UDP"]

In [100]:
udp_data.shape

(3134645, 88)

In [101]:
udp = udp_data.head(10000)

In [102]:
udp.shape

(10000, 88)

In [103]:
udp.to_csv("udp_data.csv")

In [104]:
dataset = pd.read_csv("Syn.csv")

In [105]:
dataset.shape

(1582681, 88)

In [106]:
dataset.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,281052,172.16.0.5-192.168.50.1-53058-53058-6,172.16.0.5,53058,192.168.50.1,53058,6,2018-12-01 13:30:30.741451,115799309,19,...,646237.483665,1709809.0,1.0,1.426117e+07,3.220326e+06,21714933.0,11043464.0,0,1,Syn
1,450424,172.16.0.5-192.168.50.1-32237-32237-6,172.16.0.5,32237,192.168.50.1,32237,6,2018-12-01 13:30:30.741452,113973933,16,...,19.595918,49.0,1.0,1.628198e+07,2.573891e+06,20019405.0,11993631.0,0,1,Syn
2,182979,172.16.0.5-192.168.50.1-60495-9840-6,172.16.0.5,60495,192.168.50.1,9840,6,2018-12-01 13:30:30.741501,112,2,...,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0,1,Syn
3,41540,172.16.0.5-192.168.50.1-59724-59724-6,172.16.0.5,59724,192.168.50.1,59724,6,2018-12-01 13:30:30.741563,105985004,16,...,17.705259,48.0,1.0,1.514071e+07,3.077366e+06,20954123.0,11120336.0,0,1,Syn
4,358711,172.16.0.5-192.168.50.1-60496-32538-6,172.16.0.5,60496,192.168.50.1,32538,6,2018-12-01 13:30:30.741565,1,2,...,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0,1,Syn

In [107]:
benign_data_syn = dataset[dataset[" Label"] == "BENIGN"]

In [108]:
benign_data_syn.shape

(392, 88)

In [109]:
benign_data_syn.to_csv("benign_syn.csv")

In [110]:
syn_data = dataset[dataset[" Label"] == "Syn"]

In [111]:
syn_data.shape

(1582289, 88)

In [112]:
syn = syn_data.head(10000)

In [113]:
syn.shape

(10000, 88)

In [114]:
syn.to_csv("syn_data.csv")

In [115]:
dataset = pd.read_csv("TFTP.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [116]:
dataset.shape

(20107827, 88)

In [117]:
benign_data_tftp = dataset[dataset[" Label"] == "BENIGN"]

In [118]:
benign_data_tftp.shape

(25247, 88)

In [120]:
dataset.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,46970,172.16.0.5-192.168.50.1-64670-64670-6,172.16.0.5,64670,192.168.50.1,64670,6,2018-12-01 13:34:27.403713,13120080,4,...,0.0,1.0,1.0,13120078.0,0.0,13120078.0,13120078.0,0,1,TFTP
1,164775,172.16.0.5-192.168.50.1-16405-16405-6,172.16.0.5,16405,192.168.50.1,16405,6,2018-12-01 13:34:27.404124,3990342,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,TFTP
2,177893,172.16.0.5-192.168.50.1-45838-45838-6,172.16.0.5,45838,192.168.50.1,45838,6,2018-12-01 13:34:27.404125,11842236,4,...,0.0,1.0,1.0,11842234.0,0.0,11842234.0,11842234.0,0,1,TFTP
3,82756,172.16.0.5-192.168.50.1-27049-27049-6,172.16.0.5,27049,192.168.50.1,27049,6,2018-12-01 13:34:27.404177,3579644,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,TFTP
4,153782,172.16.0.5-192.168.50.1-43305-27049-6,172.16.0.5,43305,192.168.50.1,27049,6,2018-12-01 13:34:27.404228,90,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,TFTP

In [119]:
benign_data_tftp.to_csv("benign_tftp.csv")

In [121]:
data_tftp = dataset[dataset[" Label"] == "TFTP"]

In [122]:
data_tftp.shape

(20082580, 88)

In [123]:
tftp = data_tftp.head(10000)

In [125]:
tftp.shape

(10000, 88)

In [126]:
tftp.to_csv("tftp_data.csv")

In [127]:
dataset = pd.read_csv("UDPLag.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [128]:
dataset.shape

(370605, 88)

In [129]:
benign_data_lag = dataset[dataset[" Label"] == "BENIGN"]

In [130]:
benign_data_lag.shape

(3705, 88)

In [131]:
benign_data_lag.to_csv("benign_lag.csv")

In [132]:
dataset.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,186059,172.16.0.5-192.168.50.1-58445-4463-17,172.16.0.5,58445,192.168.50.1,4463,17,2018-12-01 13:04:45.928673,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag
1,135692,172.16.0.5-192.168.50.1-36908-9914-17,172.16.0.5,36908,192.168.50.1,9914,17,2018-12-01 13:04:45.928913,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag
2,33822,172.16.0.5-192.168.50.1-41727-32361-17,172.16.0.5,41727,192.168.50.1,32361,17,2018-12-01 13:04:45.928915,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag
3,24498,172.16.0.5-192.168.50.1-55447-5691-17,172.16.0.5,55447,192.168.50.1,5691,17,2018-12-01 13:04:45.929024,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag
4,117372,172.16.0.5-192.168.50.1-58794-56335-17,172.16.0.5,58794,192.168.50.1,56335,17,2018-12-01 13:04:45.929096,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag

In [133]:
data_lag = dataset[dataset[" Label"] == "UDP-lag"]

In [134]:
data_lag.shape

(366461, 88)

In [135]:
lag = data_lag.head(10000)

In [136]:
lag.shape

(10000, 88)

In [137]:
lag.to_csv("lag_data.csv")

In [138]:
#list dataframe you want to append
frame = [benign_data_mssql, benign_data, benign_data_bios, benign_data_ntp, benign_data_snmp, benign_data_ssdp, benign_data_udp, benign_data_syn, benign_data_tftp, benign_data_lag]

#new dataframe to store append result
benign = pd.DataFrame()

for df in frame:
    benign = benign.append(df)

In [139]:
benign.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
7312,142,192.168.50.253-224.0.0.5-0-0-0,192.168.50.253,0,224.0.0.5,0,0,2018-12-01 11:32:35.074888,112597315,52,...,0.717741,7.0,4.0,9383103.25,257958.305025,9810774.0,9048572.0,0,0,BENIGN
16189,0,192.168.50.6-104.88.60.48-57271-80-6,192.168.50.6,57271,104.88.60.48,80,6,2018-12-01 11:32:37.701019,2,2,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,0,BENIGN
16190,1,192.168.50.6-104.88.29.90-57270-80-6,192.168.50.6,57270,104.88.29.90,80,6,2018-12-01 11:32:37.701021,1,2,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,0,BENIGN
16191,2,192.168.50.6-104.88.29.90-57272-80-6,192.168.50.6,57272,104.88.29.90,80,6,2018-12-01 11:32:37.701023,1,2,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,0,BENIGN
16260,3,192.168.50.6-104.88.60.48-57271-80-6,104.88.60.48,80,192.168.50.6,57271,6,2018-12-01 11:32:37.721493,1,2,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,1,BENIGN

In [140]:
benign.shape

(40803, 88)

In [141]:
benign.to_csv("benign_data.csv")

In [144]:
#list dataframe you want to append
frame = [LDAP, mssql, bios, ntp, snmp, ssdp, udp, syn, tftp, lag]

#new dataframe to store append result
my_data = pd.DataFrame()

for df in frame:
    my_data = my_data.append(df)

In [145]:
my_data.shape

(100000, 88)

In [146]:
my_data.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,21010,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:22:40.254769,9141643,85894,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
1,20932,172.16.0.5-192.168.50.1-900-1808-17,172.16.0.5,900,192.168.50.1,1808,17,2018-12-01 11:22:40.255361,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2,27876,172.16.0.5-192.168.50.1-900-58766-17,172.16.0.5,900,192.168.50.1,58766,17,2018-12-01 11:22:40.255568,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
3,24270,172.16.0.5-192.168.50.1-900-35228-17,172.16.0.5,900,192.168.50.1,35228,17,2018-12-01 11:22:40.256113,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
4,5109,172.16.0.5-192.168.50.1-900-44969-17,172.16.0.5,900,192.168.50.1,44969,17,2018-12-01 11:22:40.256285,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP

In [147]:
my_data.to_csv("my_data.csv")

In [151]:
total_data = my_data.append(benign)

In [152]:
total_data.shape

(140803, 88)

In [153]:
total_data.dropna()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,21010,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:22:40.254769,9141643,85894,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
1,20932,172.16.0.5-192.168.50.1-900-1808-17,172.16.0.5,900,192.168.50.1,1808,17,2018-12-01 11:22:40.255361,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2,27876,172.16.0.5-192.168.50.1-900-58766-17,172.16.0.5,900,192.168.50.1,58766,17,2018-12-01 11:22:40.255568,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
3,24270,172.16.0.5-192.168.50.1-900-35228-17,172.16.0.5,900,192.168.50.1,35228,17,2018-12-01 11:22:40.256113,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
4,5109,172.16.0.5-192.168.50.1-900-44969-17,172.16.0.5,900,192.168.50.1,44969,17,2018-12-01 11:22:40.256285,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278588,12564,192.168.50.6-4.2.2.4-54916-53-17,192.168.50.6,54916,4.2.2.4,53,17,2018-12-01 13:30:14.888769,20788,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
278717,278483,192.168.50.6-8.8.8.8-54916-53-17,192.168.50.6,54916,8.8.8.8,53,17,2018-12-01 13:30:14.908666,45913,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
278720,222104,192.168.50.6-4.2.2.4-50731-53-17,192.168.50.6,50731,4.2.2.4,53,17,2018-12-01 13:30:14.910274,20788,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
325145,94282,192.168.10.50-192.168.50.8-21-59982-6,192.168.50.8,59982,192.168.10.50,21,6,2018-12-01 13:30:23.154472,3009540,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,BENIGN
356474,344943,192.168.50.7-52.173.24.17-50107-443-6,192.168.50.7,50107,52.173.24.17,443,6,2018-12-01 13:30:28.385946,124327,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN

In [154]:
total_data.shape

(140803, 88)

In [155]:
total_data.to_csv("total_data.csv")

In [156]:
total_data.describe()

,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
count,140803.000000,140803.000000,140803.000000,140803.000000,1.408030e+05,140803.000000,140803.000000,140803.000000,1.408030e+05,140803.000000,...,1.408030e+05,1.408030e+05,1.408030e+05,1.408030e+05,1.408030e+05,1.408030e+05,1.408030e+05,1.408030e+05,1.408030e+05,140803.000000
mean,88793.353863,30345.526281,25756.031050,13.143321,5.729966e+06,8.824180,1.784493,2681.874818,7.017664e+02,484.740105,...,-2.351060e+07,2.288597e+04,7.681895e+03,3.398481e+04,1.829214e+04,1.541081e+06,2.289007e+05,1.874889e+06,1.313747e+06,0.751724
std,127681.325375,25859.922594,22420.060072,5.335430,2.341464e+07,311.363541,10.393897,9725.874584,1.320332e+04,570.932876,...,1.563094e+08,2.998123e+05,1.301302e+05,4.172762e+05,2.778591e+05,7.158742e+06,1.558493e+06,8.292310e+06,6.674004e+06,0.432014
min,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000e+00,0.000000,...,-1.062719e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,11408.000000,827.000000,443.000000,6.000000,1.000000e+00,2.000000,0.000000,2.000000,0.000000e+00,1.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
50%,37088.000000,38719.000000,23199.000000,17.000000,4.000000e+00,2.000000,0.000000,750.000000,0.000000e+00,369.000000,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,110876.500000,55194.000000,46822.000000,17.000000,2.335000e+04,3.000000,2.000000,2892.000000,0.000000e+00,587.000000,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,802795.000000,65534.000000,65535.000000,17.000000,1.200000e+08,85894.000000,1403.000000,108240.000000,2.757278e+06,3547.000000,...,1.480000e+03,1.721664e+07,2.853681e+07,6.783473e+07,1.721664e+07,1.192194e+08,5.275036e+07,1.192194e+08,1.192194e+08,1.000000